version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_car_crud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_car_crud
      MYSQL_USER: user_car_crud
      MYSQL_PASSWORD: root_car
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"